trigger:
  - master

pool:
  vmImage: ubuntu-latest

variables:
  dotnetVersion: 10.x
  nodeVersion: 24.x
  webAppWin64ArtifactName: dutchmetar-webapp-win-x64

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: publishWebApp
        displayName: Publish web app
        pool:
          name: emeni-build-windows
        variables:
          - group: GithubPackages
        steps:
          - task: UseDotNet@2
            displayName: Use .NET 10
            inputs:
              packageType: 'sdk'
              version: $(dotnetVersion)
              includePreviewVersions: false
              
          - task: UseNode@1
            displayName: Setup Node v$(nodeVersion)
            inputs:
              version: $(nodeVersion)

          - template: templates/nuget-config.yml

          - task: DotNetCoreCLI@2
            displayName: Run solution tests
            inputs:
              command: 'test'
              projects: 'DutchMetar.slnx'
              testRunTitle: '.NET Tests'

          - task: DotNetCoreCLI@2
            displayName: Publish DutchMetar.Web.Server (win-x64)
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: './src/DutchMetar.Web.Server'
              arguments: '-c Release -r win-x64 -o $(Build.ArtifactStagingDirectory)'
              zipAfterPublish: false
              modifyOutputPath: false

          - task: PublishBuildArtifacts@1
            displayName: Upload artifacts
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: $(webAppWin64ArtifactName)
              publishLocation: 'Container'

      - job: generateMigrations
        displayName: Generate EF migration script
        pool:
          name: emeni-build-windows
        variables:
          - group: GithubPackages
        steps:
          - task: UseDotNet@2
            displayName: Use .NET $(dotnetVersion)
            inputs:
              packageType: 'sdk'
              version: $(dotnetVersion)
              includePreviewVersions: false
              
          - task: DotNetCoreCLI@2
            displayName: Update dotnet-ef tool
            inputs:
              command: custom
              custom: 'tool'
              arguments: 'update --global dotnet-ef'
      
          - template: templates/nuget-config.yml

          - task: DotNetCoreCLI@2
            displayName: Restore solution
            inputs:
              command: 'restore'
              projects: 'DutchMetar.slnx'

          - task: DotNetCoreCLI@2
            displayName: Generate SQL migration script
            inputs:
              command: 'custom'
              custom: 'ef migrations script --idempotent --output $(Build.ArtifactStagingDirectory)/dutchmetar_mssql_migrations.sql --project ./src/DutchMetar.Infrastructure --startup-project ./src/DutchMetar.Web.Server'

          - task: PublishBuildArtifacts@1
            displayName: Upload artifact
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/ef-migrations.sql'
              ArtifactName: 'dutchmetar-db-migrations'
              publishLocation: 'Container'

      - job: publishHangfireImage
        displayName: Publish DutchMetar Hangfire image
        condition: ne(variables['Build.Reason'], 'PullRequest')
        variables:
          - group: GithubPackages
        
        steps:
          - template: templates/nuget-config.yml

          - task: Docker@2
            displayName: Build & Push
            inputs:
              containerRegistry: 'Docker Hub'
              repository: 'ultimateantic/dutchmetar-jobs'
              command: 'buildAndPush'
              Dockerfile: 'src/DutchMetar.Hangfire.Host/Dockerfile'
              buildContext: '.'
              tags: 'latest'

  - stage: deploy_test
    displayName: Deploy Test
    jobs:
      - deployment: web
        environment:
          name: Test
          resourceType: VirtualMachine
        displayName: Deploy web app
        strategy:
          runOnce:
            deploy:
              steps:

                - task: DownloadSecureFile@1
                  displayName: Download appsettings
                  name: appsettingsFile
                  inputs:
                    secureFile: 'appsettings.Test.json'


                - task: PowerShell@2
                  displayName: Move appsettings
                  inputs:
                    targetType: 'inline'
                    script: |
                      $source = '$(appsettingsFile.secureFilePath)'
                      $targetDir = '$(Pipeline.Workspace)/$(webAppWin64ArtifactName)'
                      $dest = Join-Path $targetDir 'appsettings.Production.json'
                      Move-Item -Path $source -Destination $dest -Force

                - task: IISWebAppDeploymentOnMachineGroup@0
                  inputs:
                    WebSiteName: 'test.dutchmetar.hc.emeni.nl'
                    Package: '$(Pipeline.Workspace)/$(webAppWin64ArtifactName)'
                    RemoveAdditionalFilesFlag: true
                    TakeAppOfflineFlag: true
                