// <auto-generated />
using System;
using DutchMetar.Core.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DutchMetar.Core.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DutchMetarContext))]
    [Migration("20251111153836_RemoveIsSuccess")]
    partial class RemoveIsSuccess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DutchMetar.Core.Domain.Entities.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("DutchMetar.Core.Domain.Entities.Metar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<int?>("AltimeterValue")
                        .HasColumnType("int");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DewpointCelsius")
                        .HasColumnType("int");

                    b.Property<bool>("IsAuto")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCavok")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCorrected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NoCloudsDetected")
                        .HasColumnType("bit");

                    b.Property<string>("RawMetar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("TemperatureCelsius")
                        .HasColumnType("int");

                    b.Property<int?>("VisibilityMeters")
                        .HasColumnType("int");

                    b.Property<int?>("WindDirection")
                        .HasColumnType("int");

                    b.Property<int?>("WindSpeedGustsKnots")
                        .HasColumnType("int");

                    b.Property<int?>("WindSpeedKnots")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirportId");

                    b.ToTable("Metars");
                });

            modelBuilder.Entity("DutchMetar.Core.Domain.Entities.MetarCeiling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetarId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MetarId");

                    b.ToTable("MetarCeiling");
                });

            modelBuilder.Entity("DutchMetar.Core.Domain.Entities.MetarImportResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedAirportCount")
                        .HasColumnType("int");

                    b.Property<int>("AddedMetarCount")
                        .HasColumnType("int");

                    b.Property<int>("CorrectedMetarCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FailedMetarParses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MetarImportResults");
                });

            modelBuilder.Entity("DutchMetar.Core.Domain.Entities.Metar", b =>
                {
                    b.HasOne("DutchMetar.Core.Domain.Entities.Airport", "Airport")
                        .WithMany("MetarReports")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("DutchMetar.Core.Domain.Entities.MetarCeiling", b =>
                {
                    b.HasOne("DutchMetar.Core.Domain.Entities.Metar", "Metar")
                        .WithMany("Ceilings")
                        .HasForeignKey("MetarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metar");
                });

            modelBuilder.Entity("DutchMetar.Core.Domain.Entities.Airport", b =>
                {
                    b.Navigation("MetarReports");
                });

            modelBuilder.Entity("DutchMetar.Core.Domain.Entities.Metar", b =>
                {
                    b.Navigation("Ceilings");
                });
#pragma warning restore 612, 618
        }
    }
}
